# Generated by Django 2.2.6 on 2019-10-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0002_auto_20191013_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='caption',
        ),
    ]
